# This file is part of QuickLab, which creates simple, observable labs.
# https://github.com/jeff-d/quicklab
#
# SPDX-FileCopyrightText: © 2025 Jeffrey M. Deininger <9385180+jeff-d@users.noreply.github.com>
# SPDX-License-Identifier: AGPL-3.0-or-later


locals {
  cur_prefix = "${local.module}/costreport"

  # Issue codes from POST /api/v2/integration/aws/validate_ccm_config, consumed by
  # terraform_data.datadog_ccm_config_ready below.
  # see readme.md "Terraform Implementation Details / costmanagement.tf"
  ccm_validation_ignored_issue_codes = ["S3_GET_PERMISSION_MISSING"]
  ccm_validation_terminal_issue_codes = [
    "BUCKET_NAME_INVALID_GOVCLOUD", "S3_BUCKET_REGION_MISMATCH", "TIME_GRANULARITY_INVALID",
    "FILE_FORMAT_INVALID", "INCLUDE_RESOURCES_DISABLED", "REFRESH_CADENCE_INVALID",
    "OVERWRITE_MODE_INVALID", "QUERY_STATEMENT_INVALID",
  ]

  # The full CUR 2.0 schema for the table properties set on aws_bcmdataexports_export.datadog_cur
  # below, generated by `aws bcm-data-exports get-table`.
  # see readme.md "Terraform Implementation Details / costmanagement.tf"
  cur_columns = [
    # identity
    "identity_line_item_id", "identity_time_interval",

    # bill
    "bill_invoice_id", "bill_invoicing_entity", "bill_billing_entity", "bill_bill_type", "bill_payer_account_id",
    "bill_payer_account_name", "bill_billing_period_start_date", "bill_billing_period_end_date",

    # line item
    "line_item_usage_account_id", "line_item_usage_account_name", "line_item_line_item_type",
    "line_item_usage_start_date", "line_item_usage_end_date", "line_item_product_code", "line_item_usage_type",
    "line_item_operation", "line_item_availability_zone", "line_item_resource_id", "line_item_usage_amount",
    "line_item_normalization_factor", "line_item_normalized_usage_amount", "line_item_currency_code",
    "line_item_unblended_rate", "line_item_unblended_cost", "line_item_user_identifier", "line_item_blended_rate",
    "line_item_blended_cost", "line_item_line_item_description", "line_item_tax_type", "line_item_net_unblended_rate",
    "line_item_net_unblended_cost", "line_item_legal_entity",

    # pricing
    "pricing_lease_contract_length", "pricing_offering_class", "pricing_purchase_option", "pricing_rate_code",
    "pricing_rate_id", "pricing_currency", "pricing_public_on_demand_rate", "pricing_public_on_demand_cost",
    "pricing_term", "pricing_unit",

    # product
    "product_servicecode", "product_operation", "product_usagetype", "product_sku", "product_product_family",
    "product_comment", "product_fee_code", "product_fee_description", "product_location", "product_location_type",
    "product_region_code", "product_from_location", "product_from_location_type", "product_from_region_code",
    "product_to_location", "product_to_location_type", "product_to_region_code", "product_instance_family",
    "product_instance_type", "product_instancesku", "product_pricing_unit", "product",

    # reservation
    "reservation_availability_zone", "reservation_start_time", "reservation_end_time",
    "reservation_modification_status", "reservation_amortized_upfront_cost_for_usage",
    "reservation_amortized_upfront_fee_for_billing_period",
    "reservation_unused_amortized_upfront_fee_for_billing_period", "reservation_recurring_fee_for_usage",
    "reservation_unused_recurring_fee", "reservation_effective_cost", "reservation_upfront_value",
    "reservation_net_amortized_upfront_cost_for_usage", "reservation_net_amortized_upfront_fee_for_billing_period",
    "reservation_net_unused_amortized_upfront_fee_for_billing_period", "reservation_net_recurring_fee_for_usage",
    "reservation_net_unused_recurring_fee", "reservation_net_effective_cost", "reservation_net_upfront_value",
    "reservation_normalized_units_per_reservation", "reservation_number_of_reservations",
    "reservation_reservation_a_r_n", "reservation_subscription_id", "reservation_total_reserved_normalized_units",
    "reservation_total_reserved_units", "reservation_units_per_reservation",
    "reservation_unused_normalized_unit_quantity", "reservation_unused_quantity",

    # savings plan
    "savings_plan_total_commitment_to_date", "savings_plan_savings_plan_a_r_n", "savings_plan_savings_plan_rate",
    "savings_plan_used_commitment", "savings_plan_savings_plan_effective_cost",
    "savings_plan_amortized_upfront_commitment_for_billing_period",
    "savings_plan_recurring_commitment_for_billing_period", "savings_plan_net_savings_plan_effective_cost",
    "savings_plan_net_amortized_upfront_commitment_for_billing_period",
    "savings_plan_net_recurring_commitment_for_billing_period", "savings_plan_start_time", "savings_plan_end_time",
    "savings_plan_instance_type_family", "savings_plan_offering_type", "savings_plan_payment_option",
    "savings_plan_purchase_term", "savings_plan_region",

    # split cost allocation
    "split_line_item_split_usage_ratio", "split_line_item_actual_usage", "split_line_item_reserved_usage",
    "split_line_item_split_usage", "split_line_item_split_cost", "split_line_item_unused_cost",
    "split_line_item_net_split_cost", "split_line_item_net_unused_cost",
    "split_line_item_public_on_demand_split_cost", "split_line_item_public_on_demand_unused_cost",
    "split_line_item_parent_resource_id",

    # discounts
    "discount_bundled_discount", "discount_total_discount", "discount",

    # tags and cost categories
    "resource_tags", "tags", "cost_category",
  ]
}


# S3 bucket for CURs
resource "aws_s3_bucket" "cur" {
  bucket_prefix = "${var.prefix}-${var.uid}-cur-${data.aws_region.current.region}-"
  force_destroy = true
  tags = merge(local.cloud_resource_tags,
    {
      Name = "${var.prefix}-${var.uid}-cost-reporting"
    }
  )
}

resource "aws_s3_bucket_public_access_block" "cur" {
  bucket = aws_s3_bucket.cur.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_ownership_controls" "cur" {
  bucket = aws_s3_bucket.cur.id

  rule {
    # Vestigial: Data Exports delivers via its service principal and the bucket policy, not an ACL.
    object_ownership = "BucketOwnerPreferred"
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "cur" {
  bucket = aws_s3_bucket.cur.id

  rule {
    id     = "default retention"
    status = "Enabled"
    expiration { days = 7 }
    filter {} # applies to all bucket objects
  }
}


# Bucket policy to allow CUR and BCM Data Exports services to write reports
resource "aws_s3_bucket_policy" "cur" {
  bucket = aws_s3_bucket.cur.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Principal = {
          Service = [
            "billingreports.amazonaws.com",
            "bcm-data-exports.amazonaws.com"
          ]
        }
        Action = [
          "s3:PutObject",
          "s3:GetBucketPolicy"
        ]
        Resource = [
          aws_s3_bucket.cur.arn,
          "${aws_s3_bucket.cur.arn}/*"
        ]
        Condition = {
          StringLike = {
            "aws:SourceArn" = [
              "arn:*:cur:*:${data.aws_caller_identity.current.account_id}:definition/*",
              "arn:*:bcm-data-exports:*:${data.aws_caller_identity.current.account_id}:export/*"
            ]
            "aws:SourceAccount" = data.aws_caller_identity.current.account_id
          }
        }
      }
    ]
  })
}


# CUR 2.0 export, via Billing and Cost Management Data Exports. Table configurations cannot be
# changed after creation, so get them right on the first apply.
# see readme.md "Terraform Implementation Details / costmanagement.tf"
resource "aws_bcmdataexports_export" "datadog_cur" {
  export {
    name = "${var.prefix}-${var.uid}-${local.module}-costreport"

    data_query {
      query_statement = "SELECT ${join(", ", local.cur_columns)} FROM COST_AND_USAGE_REPORT"
      table_configurations = {
        COST_AND_USAGE_REPORT = {
          BILLING_VIEW_ARN                      = "arn:${data.aws_partition.current.partition}:billing::${data.aws_caller_identity.current.account_id}:billingview/primary"
          TIME_GRANULARITY                      = "HOURLY"
          INCLUDE_RESOURCES                     = "TRUE"
          INCLUDE_SPLIT_COST_ALLOCATION_DATA    = "TRUE"
          INCLUDE_MANUAL_DISCOUNT_COMPATIBILITY = "FALSE"
        }
      }
    }

    destination_configurations {
      s3_destination {
        s3_bucket = aws_s3_bucket.cur.bucket
        s3_prefix = local.cur_prefix
        s3_region = data.aws_region.current.region

        s3_output_configurations {
          output_type = "CUSTOM"
          format      = "PARQUET"
          compression = "PARQUET"
          overwrite   = "CREATE_NEW_REPORT"
        }
      }
    }

    refresh_cadence {
      frequency = "SYNCHRONOUS"
    }
  }

  depends_on = [aws_s3_bucket.cur, aws_s3_bucket_policy.cur, aws_s3_bucket_public_access_block.cur, aws_s3_bucket_ownership_controls.cur]
  tags = merge(local.cloud_resource_tags,
    {
      Name = "${var.prefix}-${var.uid}-${local.module}-costreport"
    }
  )
}


# IAM policy for Datadog to access CUR data
resource "aws_iam_policy" "datadog_cur_access" {
  name        = "${var.prefix}-${var.uid}-${local.module}-DatadogCURAccess-policy"
  description = "Allow Datadog to access Cost and Usage Reports"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "DDCloudCostReadBucket"
        Effect = "Allow"
        Action = [
          "s3:ListBucket"
        ]
        Resource = aws_s3_bucket.cur.arn
      },
      {
        Sid    = "DDCloudCostGetBill"
        Effect = "Allow"
        Action = [
          "s3:GetObject"
        ]
        Resource = "${aws_s3_bucket.cur.arn}/${local.cur_prefix}/${aws_bcmdataexports_export.datadog_cur.export[0].name}/*"
      },
      {
        Sid    = "DDCloudCostCheckAccuracy"
        Effect = "Allow"
        Action = [
          "ce:Get*"
        ]
        Resource = "*"
      },
      {
        Sid    = "DDCloudCostListCURs"
        Effect = "Allow"
        Action = [
          "cur:DescribeReportDefinitions"
        ]
        Resource = "*"
      },
      {
        Sid    = "DDCloudCostListExports"
        Effect = "Allow"
        Action = [
          "bcm-data-exports:ListExports",
          "bcm-data-exports:GetExport"
        ]
        Resource = "*"
      },
      {
        Sid    = "DDCloudCostListOrganizations"
        Effect = "Allow"
        Action = [
          "organizations:Describe*",
          "organizations:List*"
        ]
        Resource = "*"
      }
    ]
  })
}


# Attach the policy to an existing Datadog IAM role
resource "aws_iam_role_policy_attachment" "datadog_cur_access" {
  role       = aws_iam_role.datadog_aws_integration.name
  policy_arn = aws_iam_policy.datadog_cur_access.arn
}

# Both the Datadog AWS integration and the Cloud Cost Management config validate
# access by assuming the cross-account role, so the role's policy attachments must
# be observable before either is created. They already exist per Terraform's
# dependency graph by this point, but IAM's read path is eventually consistent and
# a cross-account role-assumption may not yet observe them. Poll IAM's own read API (the same
# eventually-consistent store) for the attachment to become visible, rather than
# guessing at a fixed sleep duration -- data sources/APIs with no built-in retry
# are a known gap (https://github.com/hashicorp/terraform-provider-aws/issues/40520),
# and a local-exec provisioner gated by depends_on is the HashiCorp-recommended
# workaround, per https://github.com/hashicorp/terraform-provider-aws/issues/26026.
# datadog_integration_aws_account depends on this, so it must not be listed here.
resource "terraform_data" "datadog_aws_integration_ready" {
  depends_on = [
    aws_iam_role_policy_attachment.datadog_cur_access,
    aws_iam_role_policy_attachment.datadog_aws_integration,
  ]

  # local-exec defaults to /bin/sh, which is dash on Debian-family runners (including GitHub's
  # ubuntu-latest) and has no `-o pipefail`. Pin bash so the script's error handling holds there.
  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
    set -euo pipefail
    ATTEMPTS=0
    MAX_ATTEMPTS=30
    while true; do
      ATTACHED=$(aws iam list-attached-role-policies --role-name "$ROLE_NAME" --query "length(AttachedPolicies[?PolicyArn=='$POLICY_ARN'])" --output text 2>/dev/null || echo "0")
      if [ "$ATTACHED" != "0" ]; then
        echo "IAM policy $POLICY_ARN is attached to role $ROLE_NAME"
        break
      fi
      ATTEMPTS=$((ATTEMPTS + 1))
      if [ "$ATTEMPTS" -ge "$MAX_ATTEMPTS" ]; then
        echo "Timed out waiting for $POLICY_ARN to be attached to $ROLE_NAME" >&2
        exit 1
      fi
      sleep 10
    done
    EOT
    environment = {
      ROLE_NAME  = aws_iam_role.datadog_aws_integration.name
      POLICY_ARN = aws_iam_policy.datadog_cur_access.arn
    }
  }
}

# Gate the CCM config on Datadog's own pre-flight validator, which is what makes the propagation
# race an observable condition rather than a sleep. Requires jq, already a de facto dependency of
# this repo. datadog_integration_aws_account_ccm_config depends on this, so it must not be listed
# here.
# see readme.md "Terraform Implementation Details / costmanagement.tf"
resource "terraform_data" "datadog_ccm_config_ready" {
  depends_on = [
    aws_bcmdataexports_export.datadog_cur,
    aws_s3_bucket_policy.cur,
    datadog_integration_aws_account.datadog_integration,
    module.datadog_secrets,
  ]

  # Pinned to bash for `-o pipefail`; see terraform_data.datadog_aws_integration_ready above.
  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
    set -euo pipefail
    API_KEY=$(aws secretsmanager get-secret-value --region "$REGION" --secret-id "$API_KEY_SECRET" --query SecretString --output text)
    APP_KEY=$(aws secretsmanager get-secret-value --region "$REGION" --secret-id "$APP_KEY_SECRET" --query SecretString --output text)
    BODY=$(jq -n \
      --arg account_id "$ACCOUNT_ID" \
      --arg bucket_name "$BUCKET_NAME" \
      --arg bucket_region "$BUCKET_REGION" \
      --arg report_name "$REPORT_NAME" \
      --arg report_prefix "$REPORT_PREFIX" \
      '{data: {type: "ccm_config_validation", attributes: {account_id: $account_id, bucket_name: $bucket_name, bucket_region: $bucket_region, report_name: $report_name, report_prefix: $report_prefix}}}')
    ATTEMPTS=0
    MAX_ATTEMPTS=30
    while true; do
      RESPONSE=$(curl -sS -m 30 -w '\n%%{http_code}' -X POST \
        "https://api.$DD_SITE/api/v2/integration/aws/validate_ccm_config" \
        -H "DD-API-KEY: $API_KEY" -H "DD-APPLICATION-KEY: $APP_KEY" \
        -H "Content-Type: application/json" -d "$BODY" || true)
      HTTP_CODE=$(printf '%s' "$RESPONSE" | tail -n 1)
      PAYLOAD=$(printf '%s' "$RESPONSE" | sed '$d')

      if [ "$HTTP_CODE" = "200" ]; then
        CODES=$(printf '%s' "$PAYLOAD" | jq -r '.data.attributes.issues[]?.code' | sort -u)
        BLOCKING=""
        for CODE in $CODES; do
          case " $IGNORED_CODES " in *" $CODE "*) continue ;; esac
          case " $TERMINAL_CODES " in
            *" $CODE "*)
              echo "Datadog rejected the CUR 2.0 config for $REPORT_NAME and waiting will not help:" >&2
              printf '%s' "$PAYLOAD" | jq -r '.data.attributes.issues[]? | "  \(.code): \(.description)"' >&2
              exit 1
              ;;
          esac
          BLOCKING="$BLOCKING $CODE"
        done

        if [ -z "$BLOCKING" ]; then
          if [ -n "$CODES" ]; then
            echo "WARNING: Datadog validated $REPORT_NAME with issues that cannot clear until AWS delivers the first export files:" >&2
            printf '%s' "$PAYLOAD" | jq -r '.data.attributes.issues[]? | "  \(.code): \(.description)"' >&2
          fi
          echo "Datadog can read CUR 2.0 export $REPORT_NAME"
          break
        fi
        WAITING_ON="issues:$BLOCKING"
      elif [ "$HTTP_CODE" = "401" ] || [ "$HTTP_CODE" = "403" ]; then
        # A 404 here is the propagation race and must be retried, but bad keys never recover.
        echo "Datadog rejected the validator call for $REPORT_NAME with HTTP $HTTP_CODE: $PAYLOAD" >&2
        exit 1
      else
        WAITING_ON="HTTP $HTTP_CODE"
      fi

      ATTEMPTS=$((ATTEMPTS + 1))
      if [ "$ATTEMPTS" -ge "$MAX_ATTEMPTS" ]; then
        echo "Timed out waiting for Datadog to validate $REPORT_NAME ($WAITING_ON)" >&2
        exit 1
      fi
      sleep 10
    done
    EOT
    environment = {
      DD_SITE        = var.datadog_site
      REGION         = data.aws_region.current.region
      API_KEY_SECRET = "${var.prefix}-${var.uid}-${local.module}-api-key-workflow-automation"
      APP_KEY_SECRET = "${var.prefix}-${var.uid}-${local.module}-app-key-workflow-automation"
      ACCOUNT_ID     = data.aws_caller_identity.current.account_id
      BUCKET_NAME    = aws_s3_bucket.cur.bucket
      BUCKET_REGION  = data.aws_region.current.region
      REPORT_NAME    = aws_bcmdataexports_export.datadog_cur.export[0].name
      REPORT_PREFIX  = local.cur_prefix
      IGNORED_CODES  = join(" ", local.ccm_validation_ignored_issue_codes)
      TERMINAL_CODES = join(" ", local.ccm_validation_terminal_issue_codes)
    }
  }
}

# Register the export with Datadog Cloud Cost Management.
# see readme.md "Terraform Implementation Details / costmanagement.tf"
resource "datadog_integration_aws_account_ccm_config" "this" {
  depends_on            = [terraform_data.datadog_ccm_config_ready]
  aws_account_config_id = datadog_integration_aws_account.datadog_integration.id

  ccm_config {
    data_export_configs {
      report_type   = "CUR2.0"
      report_name   = aws_bcmdataexports_export.datadog_cur.export[0].name
      report_prefix = local.cur_prefix
      bucket_name   = aws_s3_bucket.cur.bucket
      bucket_region = data.aws_region.current.region
    }
  }
}
